version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true    
    depends_on:
      mysqldb:
        condition: service_started
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.3.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: csmaster
      MYSQL_PASSWORD: Csmaster_pw
      MYSQL_ROOT_PASSWORD: Csmaster_Rpw

networks:
  springapimysql-net:
